### ISSUE TITLE
No more working, windows is blank

### ISSUE THREAD

**Issue by vinyvince** [stefanXO/Tab-Manager-Plus#211] opened 2023-06-13 09:29 UTC
HAs stop working for me for a couple of weeeks, even after remove and add the extention, i can not see the open windows anymore, blank list, whatever i do. It was one my favorite addon

**Comment by Co3co** [comment] 2023-06-24 20:49
I am also having this issue. I'm using LibreWolf 114.0.1-2

**Comment by Rheoryn** [comment] 2023-06-27 14:22
Same issue too.  Just a blank screen, it's doing it across several, but oddly not all, of my machines now.

**Comment by KeithSware** [comment] 2023-06-29 17:33
Stopped working for me about a month ago. I was at 325 tabs at the time, but I have been up to 359 - 360 tabs before. Firefox was updated before this happened, but I don't know if this is relevant. I use this extension on other browsers and there is no problem with them, only under Firefox on windows 10. I get a white window only, it says zero tabs and zero windows momentarily before becoming a white only window. Today, I thought to re-enable it and give it another try, and, I noticed that it did start to paint lots of windows and tabs before it crashed and reverted to the white screen of death again. SO, I think there is a tab that I have open, that might be crashing the whoe story, maybe. I only think this because, ONCE, today, it did appear that it was working for about 1/2 second as it started to paint windows and tabs, then it got to something and crashed. IF ONLY, THERE WAS A LAST MINUTE POP UP WINDOW STATING THE URL THAT WAS CRASHING THE STORY, AND A LAST MINUTE EXCEPTION REPORT THAT WAS CASING THE PLUGIN TO FAIL. Then we could all report this and collectivly figure out whats causing the crash. Anyway, a try catch everything error msg popup would add value to the debugging story.

**Comment by KeithSware** [comment] 2023-06-29 18:45
The Options screen also does the same thing, it renders then 200milli seconds later, it crashes and becomes a white screen. 
![BeforeTheWhiteScreen](https://github.com/stefanXO/Tab-Manager-Plus/assets/7317145/d26325d5-7da5-463d-8d0a-3dcdc9a7a631)

I managed to capture what the options screen looks like before it crashes.

**Comment by KeithSware** [comment] 2023-06-29 19:02
Here I capture the white screens of death, notice that there are two tabs, not one tab. Before, it would make sure that only one tab existed, now you can have two tabs. So, it must crash, before the code gets to the part where it checks if it is already running in another tab.
![BeforeTheWhiteScreen](https://github.com/stefanXO/Tab-Manager-Plus/assets/7317145/956fa781-f6d9-4818-b8c7-16a10d654dd8)
Two monitors. Two browser windows, two tabs running this plug in, two white screens of death, notice that both icons for the plug in are stating that there are 340 tabs. By the way, I have been running this many tabs and more in Firefox for decades. In any event, other folks are also getting this error, I'm sure they are not running this many tabs. I'm willing to think that it might be a memory problem, but I shall be running this PC for 10 hours a day without getting any problems with anything else. The best way to find / discover what a root cause of an issue is, is to go old school, create logs and to have a try catch wrapping the entire plug in so that you have one chance to display or log something before software death.

**Comment by StarkBrothers** [comment] 2023-07-02 11:07
In the mode of "open in a own tab", i see a error "host name is undefined"
![image](https://github.com/stefanXO/Tab-Manager-Plus/assets/50072800/81241cee-d2f3-4e5e-8d64-304f1d74e500)
According tab index, i find the previous tab info, then navigate to the previous tab on address bar with "%",  really find a blank tab!!!
![image](https://github.com/stefanXO/Tab-Manager-Plus/assets/50072800/dd9f5126-9baa-4e6f-a64d-619c3999a16d)
Click it to load the tab,  but Tab Manager Plus still reports error. 
Then i find several blank tabs in the same way. Click each tab to load correctly,  it works fine finally.
So this is the firefox's problem, resulting in Tab Manager Plus not working.

**Comment by mastef** [comment] 2024-09-22 17:12
Should be fixed in 5dc30eda96037ea9626821eaa4d5fcd362d655f5 / 5.2.1

**Closed by mastef** 2024-09-22 17:12 UTC
