### ISSUE TITLE
tab groups are not saved

### ISSUE THREAD

**Issue by ghost** [stefanXO/Tab-Manager-Plus#193] opened 2022-06-15 15:14 UTC
The extension looks excellent, the problem is that if I open tabs in two windows the creation of groups is seen, but when I close the browser the groups are not saved

**Comment by octopushugger** [comment] 2022-06-21 03:54
By groups you mean individual windows? Are you expecting the tab manager to automatically save windows you close? You have to save them manually with the star button after enabling save windows for later in the settings. 

You might be looking more for a browser history manager if you want them saved automatically.

**Comment by isalew** [comment] 2022-11-02 21:03
The manager seems to only recognize windows as an organizing container unit. What the app needs to include now is an awareness of the new sub-container, [tab groups](https://blog.google/products/chrome/manage-tabs-with-google-chrome/).

**Comment by isalew** [comment] 2022-11-04 19:40
Duplicate of #16

**Comment by mastef** [comment] 2024-10-01 12:21
Duplicate of #178

**Closed by mastef** 2024-10-01 12:21 UTC
