### ISSUE TITLE
Losing windows name after restart chrome.

### ISSUE THREAD

**Issue by kittinzaa** [stefanXO/Tab-Manager-Plus#50] opened 2020-01-16 09:08 UTC
Not sure is it work before since I'm new to this addon 
but what the point to name windows if it cannot be save.

**Comment by mastef** [comment] 2020-01-16 10:08
Duplicate of #16 

@kittinzaa normally the names of the windows will be preserved. But if your Chrome or Windows crashes and you re-open Chrome - it will assign each window a new id. And then we can't match the names to the re-opened windows.

What you can do is use the "save window" feature however, which will save the windows for later - including the window title. When you restore the window from the tab manager, it will also restore the window title.

But yes, saving window titles and window colors is a feature that can be hardened with some stronger logic in the future. Right now it's just assigning names based on window ids and we rely on Chrome to keep those the same.

**Comment by kittinzaa** [comment] 2020-01-16 10:13
I close it normally not a crash by click 3 dot on the top right and exit this way will preserve all opened windows. If name save is working this addon I would call perfect though its already at best of its kind.

**Comment by anApeThrummingAViola** [comment] 2020-05-16 15:50
Similar behavior on Firefox 76.0.1, Ubuntu - when I restart my system, some or all of the page titles are lost - the contained tabs seem to be preserved though

**Comment by anApeThrummingAViola** [comment] 2020-05-20 05:05
Also, after a reboot some of the names and colors are exchanged. I have here 15 windows with 750 tabs, two windows in the foreground (which are not named). After a shutdown and restart due to system upgrade, two windows have lost their name and color), and of the remaining 11, about eight or nine had their titles and colors swapped. The colors "stayed" with "their" names.

Ubuntu 16.04.6 LTS with xfwm4, Firefox 76.0.1

**Comment by filippo-basso** [comment] 2020-06-24 10:21
Confirm, in my MacBook too, when closing Chrome (usually during a reboot), all windows names and colours are lost, even with "Save Window for Later" feature enabled (I don't understand well what this option does).

As I will need to reboot time to time, losing all the names is a bit a problem... can you please see if it's possible an easy workaround?
thank you!

**Comment by a-bronx** [comment] 2020-09-02 17:56
Same here -- normal restart of a browser (Brave) messes with titles: sometimes they all lost, sometimes one or two remain, sometimes   a title jumps to a different window.

**Comment by filippo-basso** [comment] 2020-11-22 23:44
@mastef - would be important to have a **temporary workaround**, even just a temporary file where to store windows titles & colours, if other persistence methods fails...

**Comment by mastef** [comment] 2024-09-22 17:35
Duplicate #178

**Closed by mastef** 2024-09-22 17:35 UTC
