### ISSUE TITLE
Tab group color and title not saved

### ISSUE THREAD

**Issue by tomasro27** [stefanXO/Tab-Manager-Plus#16] opened 2019-09-24 00:00 UTC
If chrome crashes, or computer restarts, the state of the tab groups is saved, but not the titles or the color. So then it becomes very hard to track what was what.
It would be great to have the titles of each group persist even when chrome crashes or computer restarts.

**Comment by mastef** [comment] 2019-09-24 04:18
@tomasro27 You are right - the reason for this is that chrome gives the new windows new ids, so the tab manager doesn't know which new windows to give the old colors to.

I'm not sure if I can fix this properly.

A better fix for this might be the saved windows https://github.com/stefanXO/Tab-Manager-Plus/issues/13

**Comment by bgolden126** [comment] 2020-03-06 11:56
Running into this issue as well... may I make a suggestion?

I use another app called Tabs Outline (https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl) primarily for crash recovery of my tabs, but I do sometimes save a window of tabs by giving it a name.

These saved windows update with tabs that I add to or remove from the window, rather than a fixed set of tabs like the saved windows in Tab Manager Plus.

Not only would this behavior resolve the issue of losing window names, but it would make saved windows more of an ongoing workflow for that project -- something I would personally find more useful than a bookmarked window of fixed tabs.

It could also be a separate feature from saved windows rather than replace it (Projects vs. Bookmarks windows?). Would be a welcome addition either way; Tabs Manager Plus has a far superior UI and usability than Tabs Outline (or any tab organization extension, for that matter!).

**Comment by olivit** [comment] 2020-05-01 15:54
Just a little variant of this issue: when I close "normally" Firefox 75 and reopen it, all the tab titles are mixed so that none of them matches the right tab group.

**Comment by vvambo** [comment] 2023-08-27 11:32
I feel "tab group" is not used consistently over the different issues. I'd talk about the browser feature of grouping tabs in a window, but I think others are talking about windows or groups in tab manager plus...

Forcing all "named & colored" windows into a new (chrome) tab group, could fix the above mentioned issue, because those are persistent even over a browser crash.

**Comment by isalew** [comment] 2024-06-20 18:49
@mastef are there any plans for the support of tab groups?

**Comment by mastef** [comment] 2024-10-01 11:48
Duplicate of #178 ( color / names of windows lost after browser restart )

Support of tab groups is not planned

**Closed by mastef** 2024-10-01 11:48 UTC
