### ISSUE TITLE
Request: Persistent Window Names

### ISSUE THREAD

**Issue by PR0CK0** [stefanXO/Tab-Manager-Plus#195] opened 2022-07-15 13:46 UTC
I use a session manager to reload all of my browser windows when starting my PC up. I use the Alt+Tab button all the time to switch between windows. In Chrome, you can name these windows by right clicking the top banner. When each window is named with one word, it makes Alt+Tabbing super quick. BUT, these window names do not persist; they disappear when you close your browser/turn off the PC. So, after restarting the browser, in the Alt+Tab menu, you see the URL of whatever tab is currently open in the window, which makes it not easy to Alt+Tab through. Your plugin allows us to name windows in the popup, but, again, the names disappear when closing the browser or shutting off the PC. This seems like a simple fix.

**Comment by mastef** [comment] 2024-10-01 11:32
Duplicate of #178 and possibly fixed in latest version

**Closed by mastef** 2024-10-01 11:32 UTC
